### ISSUE TITLE
use maintained axml dump program

### ISSUE THREAD

**Issue by eighthave** [cryptax/droidlysis#1]
There are a number of maintained AndroidManifest.xml dumpers, including at least two written in Python and are in Debian: _androguard_ and _pyaxmlparser_.  The use of axmlprinter2 should be replaced by one of those.  Then all the dependencies (except maybe _dex2jar_) would be available from Debian.

For sheer speed, there is https://github.com/avast/apkparser but that is written in Go, so it would require an exec call.

**Comment by eighthave** [comment]
Also, FYI, _androguard_ is a full DEX toolkit, so you could probably replace the _dex2jar_ calls with _androguard_ function calls in python.

**Comment by eighthave** [comment]
I guess I forgot some context here: this looks useful but a pain to setup.  It looks quite close to working with dependencies from Debian.  I've been packaging Android reversing tools for Debian, so if droidlysis got its deps from Debian, I would package it, if you thought that would be useful.

**Comment by cryptax** [comment]
>There are a number of maintained AndroidManifest.xml dumpers, including at least two written in >Python and are in Debian: androguard and pyaxmlparser. The use of axmlprinter2 should be replaced >by one of those. 

yes, you are right and I'll add that to my to-do list.

> Also, FYI, _androguard_ is a full DEX toolkit, so you could probably replace the _dex2jar_ calls with _androguard_ function calls in python.

Many of the tools I use are redundant. The fact is that some fail in some situations while others do not. When I encounter a failure, I try to fallback to another tool, which is why I wouldn't typically "replace" androguard by dex2jar, but use both.
