### ISSUE TITLE
use androguard if present

### ISSUE THREAD

**Issue by eighthave** [cryptax/droidlysis#12]
#8 7123ce7846f9a7e5a23717570713560f9367cf0e removed the use of _androguard_ entirely.  It can easily be used if it is present, so it doesn't have to be requirement.  _androguard_ is available from Debian, so there it is easy to install.  Basically, in a function, do:

```python
def get_axml():
    try:
        import androguard
        # do androguard things here
    except ImportError:
        pass
```
Or something like:
https://gitlab.com/fdroid/fdroidserver/-/blob/c78aeb39473084b3459f8212730f4e15439bdbb9/fdroidserver/common.py#L2481

_fdroidserver_ used to do that for a long time, now it requires _androguard_ because it has proven the easiest and most reliable way to get certain bits of data.  For example:

* https://gitlab.com/fdroid/fdroidserver/-/blob/c78aeb39473084b3459f8212730f4e15439bdbb9/fdroidserver/common.py#L2529
* https://gitlab.com/fdroid/fdroidserver/-/blob/c78aeb39473084b3459f8212730f4e15439bdbb9/fdroidserver/common.py#L2593
* https://gitlab.com/fdroid/fdroidserver/-/blob/c78aeb39473084b3459f8212730f4e15439bdbb9/fdroidserver/common.py#L2996

Alternatively, you might have luck with the _pyaxmlparser_ library.

**Comment by cryptax** [comment]
True, but actually, I haven't encountered a sample that apktool's XML converter couldn't process for ages, so I finished by thinking this was really overkill and could be removed altogether.

**Comment by cryptax** [comment]
At a second thought. Let me think about it.

How would you deal with optional packages for pip requirements? I don't add `androguard` in `requirements.txt`? And if it happens to be there, in the code, I use it.

**Comment by eighthave** [comment]
Yeah, exactly.  You can also add optional dependecies in _setup.py_, but I 
forget off hand how to do that.  I think it is like profiles like "dev" or "test".

**Comment by cryptax** [comment]
Actually, in this particular case, I use androaxml from the command line, so checking `import androguard` is useless. But if `androaxml.py` is not present I catch the error, log it and continue.
