### ISSUE TITLE
KeyError: 'tools'

### ISSUE THREAD

**Issue by gusgravious** [cryptax/droidlysis#13]
I am trying to run droidlysis as distributed with Remnux and I am recieving an error:

```
Traceback (most recent call last):
  File "/user/local/bin/droidlysis", line 9 in <module>
    droidlysis3.process_input(args)
  File "/usr/local/packagesbin/droidlysis3.py", line 105, in process_input
    config = generalconfig(filename=args.config, verbose=args.verbose)
  File "/usr/local/lib/python3.8/dist-packages/droidconfig.py", line 15, in __init__
    self.APKTOOL_JAR = self.config['tools']['apktool']
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'tool'
```
This may very well be more of an "me" problem, though I thought I'd at least ask if this is something I can fix.

Current and up-to-date Remnux install, Version 3.4.3 of droidlysis.

**Comment by cryptax** [comment]
Hi @gusgravious this sounds like your `./conf/general.conf` is missing the apktool entry: `apktool = YOURDIR/apktool_2.7.0.jar`. 
Do you have this?

**Comment by gusgravious** [comment]
Thank you very much, there were two issues. I found the general.conf file and that line was there.

[tools]
apktool = /home/axelle/softs/apktool_2.7.0.jar
baksmali = /home/axelle/softs/baksmali-2.5.2.jar
dex2jar = /home/axelle/softs/dex-tools-2.2-SNAPSHOT/d2j-dex2jar.sh
procyon = /home/axelle/softs/procyon-decompiler-0.5.30.jar
keytool = /usr/bin/keytool

Issue one, apktool, baksmali, dex-tools and procyon were all symlinked in usr/bin so they were on the system but using different names and were different versions.
Issue two, since this was a Remnux VM, the folder /home/axelle does not exist. Closes reasonable should be /home/remnux. Following the installation instruction using pip from github/pypi, the general.conf still points to /axelle.

I just used --config option pointing to a new general.conf file with the /home/remnux path to "tools" and it worked.

**Comment by cryptax** [comment]
Modified with use of `~`. And `droidlysis` will complain explicitly if it can't find the tools.

**Comment by gusgravious** [comment]
Sorry for a really late reply. Thank you for fixing this and for maintaining a really nice tool!
