### ISSUE TITLE
AttributeError: module 'logging' has no attribute 'verbose'

### ISSUE THREAD

**Issue by digitalsleuth** [cryptax/droidlysis#15]
Good evening,

Hate to be 'that guy', but after you fixed the most recent issue regarding verbose mode, two new issues popped up. This particular one is as follows:
```bash
$ droidlysis --config /usr/local/lib/python3.8/dist-packages/conf/general.conf -i Signal-Android-website-prod-universal-release-6.19.8.apk -o .
Traceback (most recent call last):
  File "/usr/local/bin/droidlysis", line 9, in <module>
    droidlysis3.process_input(args)
  File "/usr/local/bin/droidlysis3.py", line 106, in process_input
    config = generalconfig(filename=args.config, verbose=args.verbose)
  File "/usr/local/lib/python3.8/dist-packages/droidconfig.py", line 40, in __init__
    logging.verbose(f'Copying {self.DISTRIB_KIT_CONFIGFILE}'
AttributeError: module 'logging' has no attribute 'verbose'
```

I did confirm by importing logging that `verbose` is not an available option. Looks like this might have been introduced in [09c1f60](https://github.com/cryptax/droidlysis/commit/09c1f60f987e1ff7f14ae876ab751aa715290a59).

The other issue will be raised separately.

Cheers!

**Comment by cryptax** [comment]
> Hate to be 'that guy'

You shouldn't :wink:  Rather, shame on me not to have noticed this one through testing. I tested with a config file already created so did not notice this error.

It's fixed.
