### ISSUE TITLE
procyon-decompiler-0.5.30.jar not found

### ISSUE THREAD

**Issue by Siletskiy** [cryptax/droidlysis#19]
root@f011eaf1b10d:/opt/droidlysis# python3 droidlysis --input ./mysample.apk --output . --config /opt/droidlysis/conf/general.conf

WARNING:droidconfig.py:Cannot access /opt/procyon-decompiler-0.5.30.jar - check your configuration file /opt/droidlysis/conf/general.conf
END

**Comment by cryptax** [comment]
Hi, sorry for the late reply, I should really turn notifications on...

Procyon is an external tool which is now difficult to find, I have added it to my repository here.
https://github.com/cryptax/droidlysis/blob/master/external/procyon-decompiler-0.5.30.jar

DroidLysis works also fine without Procyon, it just does not decompile the DEX, only disassembles it.
