### ISSUE TITLE
use standard Python setup.py instead of Makefile

### ISSUE THREAD

**Issue by eighthave** [cryptax/droidlysis#3]
The standard way to build/make a Python package is _setup.py_  It is in Python and is quite simple and well documented.  This project should get rid of the _Makefile_ and use the standard _setup.py_.  Then it can easily be published and installed with _pip_ and any distro package can trivially use the _setup.py_.

**Comment by cryptax** [comment]
you are right. I will do that. Soon :)

**Comment by eighthave** [comment]
excellent!  You might have guessed, I'm thinking of packaging this for
Debian.  Having these things in place makes it that a lot less work.

**Comment by cryptax** [comment]
This is partly solved in commit 5c1fdaab044079c05a925f7fb145740e5f425356.
However, there are several softs, like Baksmali, Dex2jar or Procyon that I do not know how to include in `setup.py` requirements as they are non-Python code, nor git (doc: https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi).

If you have any idea how to do that properly, let me know :)

**Comment by eighthave** [comment]
I don't know of a way to handling non-Python dependencies in _setup.py_.  One approach is making the Python runtime code detect those, and only use them if they are present.  If they are hard requirements, then I guess it needs to just quit with an error and perhaps give a URL to install instructions. 

This is where Debian packaging comes in: it can specify and install all of the dependencies.  I think most of the ones _droidlysis_ needs are already in Debian.  I think only _dex2jar_ is missing.
