### ISSUE TITLE
make dex2jar optional?

### ISSUE THREAD

**Issue by eighthave** [cryptax/droidlysis#5]
I have just packaged DroidLysis for Debian and uploaded it for inclusion.  All of the dependencies are already in Debian except for _dex2jar_ and _procyon_.  Unfortunately _dex2jar_ looks like a lot of work to package and _baksmali_ should cover a lot of use cases already.   Would it be possible to make _dex2jar_ optional?  The good news is that _procyon_ looks easy to package, if that helps.

The source for the Debian package will turn up here soon:
https://salsa.debian.org/python-team/applications/droidlysis

**Comment by cryptax** [comment]
Yes, making dex2jar optional is do-able. It's a pity though because then you can use the jar in Java Decompilers. But I can do it (asap).

**Comment by eighthave** [comment]
Great!  There is no question that having dex2jar there is good.  Having
working droidlysis is better than nothing, IMHO.  One of my goals is to
get more people doing this kind of analysis, having `apt-get install
droidlysis` means many more people can just install and run to get
results.  And installing the dex2jar binary will not be harder in this
Debian setup, it just needs to be installed and unzipped into a folder.
 I suppose there could even be `droidlysis --fetch-dex2jar` to do it
automatically.

That is also not to say that dex2jar will not ever be included in
Debian.  Right now, we're working on getting Kotlin and the latest
Android SDK in.  If we have time left over in the next few months, we
can look at dex2jar, but I must say it is unlikely there will be extra
time since the Android SDK is full of surprises.

**Comment by cryptax** [comment]
I have added this, and from my basic tests, it works.
In the configuration, set `DEX2JAR_CMD` to a non-existent file, and Dex2Jar will be reported as missing, and skipped.
