### ISSUE TITLE
Procyon (procyon-decompiler) moved from Bitbucket to Github

### ISSUE THREAD

**Issue by mavjs** [cryptax/droidlysis#6]
Hi,

The author of Procyon has moved from [Bitbucket](https://bitbucket.org/mstrobel/procyon/src/master/) to [Github](https://github.com/mstrobel/procyon).
![image](https://user-images.githubusercontent.com/881987/103277064-74651300-49c8-11eb-9a5e-15d98cc01c38.png)

However, they do not provide downloadable jar files anymore on either Bitbucket or Github. Although I do see that it can possibly be built using `./gradlew build` command as seen in their [bitbucket-pipelines.yml](https://github.com/mstrobel/procyon/blob/develop/bitbucket-pipelines.yml)

I think it would be nice to verify and document how to compile procyon-decompiler.jar, and remove the `wget procyon-decompiler` part in the README.

I'm willing to try and contribute that part. What do you think?

**Comment by cryptax** [comment]
yes, I'll remove the dependance to procyon for now - at least until they provide a clean way to compile (it fails) or releases.

**Comment by cryptax** [comment]
this is fixed in commit: 6493e308ae6ae3ccac24e6950148d2aafbd11bf0
